;; Test for aoc2025.day7
(ns aoc2025.day07-test
  (:require [aoc.day :refer [day-answers]]
            [aoc2025.day07 :as d]
            [clojure.test :refer :all]))

(def example
  ".......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............")

(deftest part1-example
  (is (= 21 (d/part1 example))))

(deftest part2-example
  (is (= 40 (d/part2 example))))

(def answers (delay (day-answers 2025 7)))
(def input (delay (d/input)))

(deftest part1-correct
  (is (= (:answer1 @answers) (d/part1 @input))))

(deftest part2-correct
  (is (= (:answer2 @answers) (d/part2 @input))))
